New solana reader
debridge-finance/debridge-node pull request #56
Opened 2023-05-22 08:44 UTC by mncdg

## How to update to v2.6.0
### Pull latest changes
```shell
git checkout master
git pull origin master
```
### Update env
Add new variables
```
POSTGRES_SOLANA_READER_DATABASE=solana${PG_RANDOM_ID}
DEBRIDGE_PROGRAM_PUBKEY=DEbrdGj3HsRsAzx6uH4MKyREKxVAfBydijLUF3ygsFfh
DEBRIDGE_SETTINGS_PROGRAM_PUBKEY=DeSetTwWhjZq6Pz9Kfdo1KoS5NqtsM6G8ERbX4SSCSft

RUST_LOG=info,tokio_util=warn,hyper=warn

# TODO: update with your RPC HTTP
DEBRIDGE_EVENTS_SOLANA_CLUSTER=
# TODO: update with your RPC WSS
DEBRIDGE_EVENTS_SOLANA_WEBSOCKET_CLUSTER=

DEBRIDGE_EVENTS_RESYNC_SIGNATURES_CHUNK_SIZE=5
DEBRIDGE_EVENTS_CONSISTENCY_CHECK_TIMEOUT_SECS=10
DEBRIDGE_EVENTS_DB_REQUERY_TIMEOUT_IN_SEC=5
DEBRIDGE_EVENTS_HEARTBEAT_TIMEOUT_IN_SEC=30

SOLANA_GRPC_SERVICE_URL=solana-grpc-service${DOCKER_ID}:7777
DEBRIDGE_SOLANA_EVENTS_PSQL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_SOLANA_READER_DATABASE}
```

Delete old variables
```
SOLANA_DATA_READER_PORT
SOLANA_RPC
DEBRIDGE_PK
SETTINGS_PK
SOLANA_DATA_READER_API_BASE_URL
SOLANA_DATA_READER_API_SENTRY_DSN
SOLANA_GET_HISTORICAL_BATCH_SIZE
SOLANA_GET_EVENTS_BATCH_SIZE
SOLANA_API_REQUEST_TIMEOUT
SOLANA_API_WAIT_BATCH_INTERVAL

```
### Create new database "solana_0" for solana-events-reader
1. First, you need to get into the Docker container's shell. You can do that with the following command:
bash
```
docker exec -it <container-id-or-name> bash
```
Replace <container-id-or-name> with your container's ID or name.

2. Once you're inside the container, you can connect to the PostgreSQL server using the psql command-line interface:
bash
```
psql -U <username> -d <database>
```
Replace <username> with the PostgreSQL username (e.g., postgres), and <database> with the name of an existing database (e.g., postgres).

3. Now that you're connected to the PostgreSQL server, you can execute your CREATE DATABASE command:
sql
```
CREATE DATABASE solana_0;
```

4. You can exit psql with the command \q, and then exit the Docker container's shell with the command exit.

2023-05-23 08:00 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/TransformService.ts
> +    submission.submissionId = U256Converter.toBytesBE(sendEvent.submissionId).toString('hex');
Will generate hex string without 0x prefix!

2023-05-23 08:01 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/TransformService.ts
> +    submission.txHash = sendEvent.transactionMetadata.transactionHash.toString('hex');
Same for prefix

2023-05-23 08:02 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/TransformService.ts
> +    submission.receiverAddr = sendEvent.submission.receiver.toString('hex');
Same for prefix

2023-05-23 08:02 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/TransformService.ts
> +    submission.debridgeId = U256Converter.toBytesBE(sendEvent.submission.bridgeId).toString('hex');
Same for prefix

2023-05-23 08:04 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +    await this.#duplex?.requests?.complete();
Don't really need to call complete since you're not sending any data to duplex

2023-05-23 08:07 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +      if (!(response.sendEventMessage !== undefined && response.sendEventMessage.oneofKind !== undefined)) {
Hard to read, 
`!(sendEventMessage !== undefined && sendEventMessage.oneofKind !== undefined)` -> `if (sendEventMessage?.oneofKind === undefined) continue`

2023-05-23 08:12 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +      this.createSubscription();
You don't need to re-create subscription on every heartbeat, grpc already have `heartbeat` events.
Use setInterval with binded value (e.g. isAlive), update value on every event (heartbeat or data) `isAlive = true`, throw error if interval ticks but isAlive = false

```ts
checkHeartbeat() {
if (!this.isAlive) {
  throw new Error();
}
this.isAlive = false; // will be set to true when event will be received
}

setInterval(this.checkHeartbeat.bind(this), timeout)
```

2023-05-23 08:18 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +        this.#submissionsFromSync = [];
Don't need to rewrite array twice, see line 53

2023-05-24 08:49 UTC, devDesu requested changes

2023-05-24 08:49 UTC, devDesu commented on debridge_node/src/modules/chain/scanning/services/TransformService.ts
> +    submission.txHash = sendEvent.transactionMetadata.transactionHash.toString('hex');
0x prefix missing

2023-05-24 08:54 UTC, devDesu commented on debridge_node/src/modules/jobs/services/actions/CheckAssetsEventAction.ts
> +    this.#account = this.web3Service.web3().eth.accounts.decrypt(JSON.parse(readFileSync('./keystore.json', 'utf-8')), process.env.KEYSTORE_PASSWORD);
@mncdg https://github.com/debridge-finance/debridge-node/issues/57
Please mark conversation as resolved when you'll check the issue

2023-05-24 10:04 UTC, devDesu approved these changes

2023-05-24 13:38 UTC, b33ngo requested changes
Can you describe some high-leve logic how this sevice works with solana events reader. A Code that  I saw doesn't like logic that have to be on client side. A Code that I saw doesn't see like logic that have to be on client side. You have subscribe on get_solana events and if subscription fails, you have to resubscribe with correct start nonce to not skip some events

2023-05-24 13:38 UTC, b33ngo commented on .default.env
> +DEBRIDGE_SETTINGS_PROGRAM_PUBKEY=todo
Can be removed

2023-05-24 13:38 UTC, b33ngo commented on .default.env
> +DEBRIDGE_SETTINGS_PROGRAM_PUBKEY=todo
DEBRIDGE_SETTINGS_PROGRAM_PUBKEY and DEBRIDGE_PROGRAM_PUBKEY

2023-05-24 13:38 UTC, b33ngo commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +          this.heartbeat();
Why do you subscribe on hearbeat there?

2023-05-24 13:38 UTC, b33ngo commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +          break;
Why do you break after first event receiving? Grpc have to return stream with events

2023-05-24 13:38 UTC, b33ngo commented on debridge_node/src/modules/chain/scanning/services/SolanaReaderService.ts
> +        this.createSubscription();
Can you describe this logic. It's not clear for me. Why do you create subscribe if sync process return error?

2023-06-13 20:37 UTC, artyukh commented on .default.env
>  DEBRIDGE_PK=DEbrdGj3HsRsAzx6uH4MKyREKxVAfBydijLUF3ygsFfh
@mncdg Check all obsolete env
SOLANA_DATA_READER_PORT
SOLANA_RPC
DEBRIDGE_PK
SETTINGS_PK

2023-06-14 15:30 UTC, b33ngo approved these changes

2023-06-15 14:00 UTC, cyphersnake requested changes
Please answer for @b33ngo questions here, I need this answers too

2023-06-20 11:25 UTC, devDesu requested changes

2023-06-22 10:10 UTC, devDesu approved these changes

2023-06-22 11:42 UTC, devDesu approved these changes

2023-06-22 20:00 UTC, merged